export default {
  "login": "suraj9318",
  "id": 111958094,
  "node_id": "U_kgDOBqxYTg",
  "avatar_url": "https://avatars.githubusercontent.com/u/111958094?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/suraj9318",
  "html_url": "https://github.com/suraj9318",
  "followers_url": "https://api.github.com/users/suraj9318/followers",
  "following_url": "https://api.github.com/users/suraj9318/following{/other_user}",
  "gists_url": "https://api.github.com/users/suraj9318/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/suraj9318/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/suraj9318/subscriptions",
  "organizations_url": "https://api.github.com/users/suraj9318/orgs",
  "repos_url": "https://api.github.com/users/suraj9318/repos",
  "events_url": "https://api.github.com/users/suraj9318/events{/privacy}",
  "received_events_url": "https://api.github.com/users/suraj9318/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Suraj Mishra",
  "company": null,
  "blog": "https://suraj9318.netlify.app/",
  "location": "New Delhi",
  "email": null,
  "hireable": true,
  "bio": " I am a enthusiastic front-end developer and have been in the industry for more than 1.4 years.",
  "twitter_username": null,
  "public_repos": 15,
  "public_gists": 0,
  "followers": 13,
  "following": 1,
  "created_at": "2022-08-24T06:54:08Z",
  "updated_at": "2023-02-06T17:00:10Z"
};
